{
    "name": "Riverflow",
    "version": "19.0.1.1199",  # 19.0.1.1198: workflow cleanup + icon fix (icon-audit 2026-08-10, usage checked on crmain). Send Notification fa-envelope -> fa-bell (Send Email owns the envelope; both sit side by side in the picker, the bell marks the one-shot variant; noupdate=1 file -> migration pushes it, guarded on the shipped value). RETIRED the "To Be Invoiced" workflow stub: never went live (zero services on crmain, transitions never uncommented) and its fa-file-invoice-dollar icon was FA5-only — Odoo ships FontAwesome 4.7, so it rendered as an EMPTY box; XML file removed, migration deletes the noupdate rows (guarded: skips if services exist). Migration also archives the hand-made "AB Appointment (Do not use, work in progress)" workflow found on crmain (UI-created, no xml id, zero services — superseded by the real Arrange Work Permit workflow; matched by exact name + no-xmlid + no-usage). New tests/test_workflow_icons.py validates EVERY riverflow.workflow/transition/transition-action icon class against the FA 4.7 css shipped with Odoo, so FA5-only names can no longer slip in unnoticed.  # 19.0.1.1196: auto-add engine — candidate-aware dedup + single-open guard. Filter hooks may REDIRECT candidates to a different subject than the trigger model (rivercreds credential-subject rules anchor the service on the credential's holder); the dedup and open-service lookups now group candidates by their own res_model and key on (rule, res_model, res_id, context_ref) instead of searching only the trigger model, so redirected candidates no longer escape dedup on re-evaluation. Behaviour-neutral when no hook rewrote candidates.  # 19.0.1.1182: WP renewal waiver (Phase C / R1+R5a) — generic delete/archive guard on riverflow.service: `_single_open_removal_blocked()` refuses unlink (and manual archive) of an `is_open` service on an `enforce_single_open` workflow that is past its initial state OR still has live (active, non-end-state) child services. A childless initial-state monitoring service stays removable (self-heals in crewradar_creds). See rivercreds/references/golden-rules-and-waivers.md R1.
    "depends": ["base", "mail", "documents", "oteny_shortcut"],
    "author": "Vriend Studio",
    "category": "Workflow",
    "description": """
    Task manager for the Service Industry
    """,
    # data files always loaded at installation
    "data": [
        "security/riverflow_security.xml",
        "security/ir.model.access.csv",
        "data/riverflow_teams_data.xml",
        "wizards/riverflow_transition_wizard_view.xml",
        "wizards/riverflow_service_wizard_view.xml",
        "wizards/riverflow_start_service_view.xml",
        "wizards/riverflow_service_email_sender_view.xml",
        "wizards/riverflow_service_register_wizard_view.xml",
        "wizards/riverflow_supplier_confirmed_view.xml",
        "wizards/riverflow_enter_train_ticket_view.xml",
        "wizards/riverflow_enter_airline_ticket_view.xml",
        "wizards/riverflow_enter_distance_wizard_view.xml",
        "wizards/riverflow_set_deadline_tomorrow_wizard_view.xml",
        "wizards/riverflow_verify_trip_locations_wizard_view.xml",
        "views/riverflow_service_views.xml",
        "views/riverflow_workflow_views.xml",
        "views/riverflow_state_views.xml",
        "views/riverflow_transition_views.xml",
        "views/riverflow_transition_action_views.xml",
        "views/riverflow_state_record_views.xml",
        "views/riverflow_team_views.xml",
        "views/riverflow_auto_add_domain_views.xml",
        "views/riverflow_auto_add_service_views.xml",
        "views/riverflow_check_result_views.xml",
        "views/res_config_settings_views.xml",
        "data/transition_action_data.xml",
        "data/workflow_service_task.xml",
        "data/service_email_workflow.xml",
        "data/service_send_notification_workflow.xml",
        "data/service_arrange_and_send_workflow.xml",
        # "data/riverflow_back_office_workflow.xml",
        "data/riverflow_taxi_order_workflow.xml",
        "data/riverflow_taxi_leg_workflow.xml",
        "data/riverflow_train_ticket_workflow.xml",
        "data/ir_config_parameter_data.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "riverflow/static/src/components/**/*",
            # Dark mode files load via web.assets_web_dark only
            (
                "remove",
                "riverflow/static/src/components/timeline/timeline_scale_selector.dark.scss",
            ),
            "riverflow/static/src/patch/**/*",
            "riverflow/static/src/riverflow_force_xl.js",
            "riverflow/static/src/scss/bg-decorations.scss",
        ],
        "web.assets_web_dark": [
            "riverflow/static/src/components/timeline/timeline_scale_selector.dark.scss",
        ],
        "web.assets_unit_tests": [
            "riverflow/static/tests/**/*",
        ],
    },
    "application": True,
    "auto_install": False,
    "license": "OEEL-1",
}
